services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'

  mongodb:
  container_name: mongoDB
  image: mongo:8.0-rc
  environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=secret
  networks:
    - database_network
    - mongo_network
  # volumes:
  # -  need to figure out  

mongo-express:
  container_name: mongoExpress
  restart: always
  image: mongo-express:1.0-20-alpine3.19
  environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=secret

  networks:
    - mongo_network

    # dont need port forwarding nothing needs to be accessed from outside 

    # volumes:
    # -  need to figure out  


redis:
    container_name: redis
    image: redis:alpine  
    networks:
      - movie_api_network




networks:
  database_network:
    driver: bridge

  movie_api_network:
    driver: bridge

  mongo_network:
    driver: bridge
