services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'

networks:
  database_network:
    driver: bridge

  movie_api_network:
    driver: bridge

  internal_network:
    driver: bridge
